# Generated by Django 4.2.3 on 2023-07-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee_info",
            name="employee",
        ),
        migrations.AddField(
            model_name="employee_info",
            name="experience",
            field=models.TextField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee_info",
            name="skills",
            field=models.TextField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
