# Generated by Django 4.0.5 on 2023-07-09 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('job_description', models.TextField(max_length=250)),
                ('job_location', models.CharField(max_length=250)),
                ('job_salary', models.CharField(max_length=250)),
                ('job_experience', models.CharField(max_length=250)),
                ('job_qualification', models.CharField(max_length=250)),
                ('job_posted_on', models.DateField(auto_now_add=True)),
                ('job_type', models.CharField(max_length=250)),
                ('job_posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
