# Generated by Django 4.2.3 on 2023-07-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_employee_info_employee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobinsightdata",
            name="csv_file",
        ),
        migrations.AddField(
            model_name="jobinsightdata",
            name="job_application_data",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="jobinsightdata",
            name="job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="account.jobpost"
            ),
        ),
    ]
