# Generated by Django 4.2.3 on 2023-07-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_jobinsightdata_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="job_data",
            field=models.JSONField(null=True),
        ),
    ]
