wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.5
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1690133127.552534
    t:
      1:
      - 55
      - 86
      - 97
      2:
      - 55
      - 86
      - 97
      3:
      - 23
      4: 3.11.2
      5: 0.15.5
      8:
      - 1
      - 2
      - 4
      - 5
      9:
        2: langchain
